### ISSUE TITLE
Table drawing problem in windows

### ISSUE THREAD

**Issue by dkushnikov** [phprtflite/PHPRtfLite#11]
I have some problem in windows in standard wordpad application: when I draw table I see only one (first) row in document. Other rows and any content after it doesn't appear.

I try sample from source and problem occurred too.

I can see problem only in Windows. Everything is good at Mac.
Can you help me with this?

**Comment by stevennikolic** [comment]
Does the error occur when you view it in different client environments or when you create it in different server environments?

**Comment by dkushnikov** [comment]
No. Error occur only in Windows Environment in Wordpad and Word.
Can't tell anything about another server configuration: I use php5.4 on ubuntu 12.04

**Comment by dkushnikov** [comment]
Hi again. Do you have any ideas?
Were you able to reproduce the error?

**Comment by sigma-z** [comment]
Hi, do you have sample code, so that I can reproduce that issue?

**Comment by dkushnikov** [comment]
I used table sample from repository (https://github.com/phprtflite/PHPRtfLite/blob/master/samples/tables.php).

**Comment by sigma-z** [comment]
Which MS Word version are you using?

**Comment by dkushnikov** [comment]
I'm using WordPad from Windows 7

**Comment by peeweehaa** [comment]
Anything on this issue ? I have the same type of problem.
I make a RTF document on a Mac. No problems opening it in Word for Mac. But when i open the same document in WordPad on Windows, i only see the outline of the table in the header.

**Comment by sigma-z** [comment]
I'm not totally sure, but I think, WordPad has only a very rudimentary table support. And they may the reason for the problems you habe. Do not use WordPad as RTF-Reader, because not all RTF features are supported.

Sorry guys :-(

**Comment by ctrlaltca** [comment]
Using the demo file provided here: https://raw2.github.com/phprtflite/PHPRtfLite/master/samples/generated/tables.rtf

This is the result on wordpad/winxp:
![wordpad](https://f.cloud.github.com/assets/1631111/2184784/8c2e64e2-97c7-11e3-9105-b393be0593e7.gif)

**Comment by ctrlaltca** [comment]
Same file, Wordpad on Windows 7: all the content after the first row is missing:
![w7](https://f.cloud.github.com/assets/1631111/2184856/0cc3013e-97c9-11e3-993c-b2be7082254c.gif)

**Comment by ctrlaltca** [comment]
Tested WordPad on Windows8.1 and the file gets rendered correctly.

**Comment by peeweehaa** [comment]
When i open that document, i only see the first row... 
Im an not very well known in the structure of RTF, but can anyone tell me what is wrong with this document : www.bouworganizer.nl/test/test.docx
I can open it without a problem in Word Mac, but openoffice gives me an input error.

**Comment by ctrlaltca** [comment]
It works on LibreOffice 4.2, anyway it's totally unrelated to PHPRtfLite so please don't pollute this ticket.

**Comment by peeweehaa** [comment]
I dont know what it is related to so sorry if i polute this topic, but i made the document using PHPRtfLite following the guidelines in the documentation

**Comment by peeweehaa** [comment]
Ok,  i fixed it. I wasnt PHPRtfLite lite indeed. It was a typo in my code that got mixed up in my versioncontrol. Thanks anyway for the help and answers and this great library !
