### ISSUE TITLE
Composer 1.3.2 not found

### ISSUE THREAD

**Issue by ovr** [phprtflite/PHPRtfLite#18]
https://packagist.org/packages/phprtflite/phprtflite

**Comment by ovr** [comment]
@sigma-z ping

**Comment by stevennikolic** [comment]
how to reproduce this?

composer require phprtflite/phprtflite dev-master
or
composer require phprtflite/phprtflite 1.3.1

are working without any problem for me

**Comment by ovr** [comment]
@stevennikolic 
See https://github.com/phprtflite/PHPRtfLite/releases 1.3.2 release
But packagist is not sync with rep auto

**Comment by keanor** [comment]
Please, send 1.3.2 to packagist ( https://packagist.org/packages/phprtflite/phprtflite )

**Comment by sigma-z** [comment]
Please use v1.3.3, which is available on packagist now...
