### ISSUE TITLE
Duplicate \trowd in Table.php 

### ISSUE THREAD

**Issue by ctrlaltca** [phprtflite/PHPRtfLite#2]
In Table.php, both render() and renderRowDefinition() writes the \trowd tag, creating a duplicate.
I saw commit 062170f0629a93cff4ef78300e36c4d4d6bd175a contains "Removed duplicate \trowd in Table.php" in the description and all the samples have been regenerated correctly, but it seems that the change did not make its appearance into the code.

The patch is trivial:

``` diff
Index: lib/PHPRtfLite/Table.php
===================================================================
--- lib/PHPRtfLite/Table.php    (revision 74)
+++ lib/PHPRtfLite/Table.php    (working copy)
@@ -872,7 +872,6 @@
         $stream = $this->getRtf()->getWriter();

         foreach ($this->_rows as $row) {
-            $stream->write('\trowd');
             $this->renderRowDefinition($row);
             $stream->write("\r\n");
             $this->renderRowCells($row);
```

**Comment by sigma-z** [comment]
Fixed for master branch

**Comment by ctrlaltca** [comment]
This issue has been closed but the actual patch did not get applied in lib/PHPRtfLite/Table.php.

**Comment by sigma-z** [comment]
Fixed for the master branch
