### ISSUE TITLE
File start {\rtf instead of {\rtf1

### ISSUE THREAD

**Issue by DanidCH** [phprtflite/PHPRtfLite#22]
I'm using your library to convert HTML from our ticketing system to transform it in RTF to be used in our ERP. For some reason during an update their RTF parser hardened it's rules and doesn't accept "{\rtf" as a file start anymore, it needs to start with "{\rtf1" which seems to be in the RTF definition.

Where could I change this? I've already searched the code for the portion of text but can't seem to find it.

**Comment by ctrlaltca** [comment]
Here it is: https://github.com/phprtflite/PHPRtfLite/blob/master/lib/PHPRtfLite.php#L1396

**Comment by DanidCH** [comment]
That was quick! Thank you very much! Can't understand why my search function didn't work on this file...
