### ISSUE TITLE
problem with unicode character in footnote

### ISSUE THREAD

**Issue by a9b8c2** [phprtflite/PHPRtfLite#3]
the PHPRtflite has no problem with unicode in writing paragraph regular text, but if the text is in the footnote, the text is not show correctly. see the attached image for example.
![2013-01-16_163640](https://f.cloud.github.com/assets/3258793/71228/a8f0af86-5fdd-11e2-942f-a0680b6959b0.png)

**Comment by sigma-z** [comment]
May you provide me your input or sample data then I could try to reproduce that problem

**Comment by sigma-z** [comment]
Should be fixed now, please let me know if you still have problems.
