### ISSUE TITLE
Spurious \par emitted on empty writeText('') calls

### ISSUE THREAD

**Issue by ctrlaltca** [phprtflite/PHPRtfLite#4]
Cosider the following example of code:

```
$page->writeText($text)
```

It adds an element to the rtf that renders to simple text with optional formating.
But if $text=='', phprtflite will write a \par that will result visually in a newline.
I didn't find any documentation citing this, sow hile it's not a big problem i suppose it's not the wanted behaviour.
This gets boring when working with table cells, since the newline will cause the cell height to double.
I've created a patch: 6747f3bb0a, i can't understand why that \par was introduced at all so i'm unsure about the possible breakage, even if i didn't notice any problem with my rtf.

**Comment by sigma-z** [comment]
If you are interested in my fix take a look at 2debf4b06e4b5bcfbdf64a7ff42d02ab89bd53d7.
There was an edge case, where your fix did not work properly.
