### ISSUE TITLE
Normal Text followed by Enumeration => Problem

### ISSUE THREAD

**Issue by igigithub** [phprtflite/PHPRtfLite#7]
When I have normal Text followed by an enumeration, the normal text gets enumerated too.

// Not working:
$enum = new PHPRtfLite_List_Enumeration($rtf, 4);
$enum->addItem('hello world');
$enum->addItem('foo');
$enum->addItem('bar');

$cell = $table->getCell(1, 1);
$cell->writeText('This text gets formated as an Enumeration too', $font, $paragraph);
$cell->addList($enum);

// Working
// but generates an empty line
$cell = $table->getCell(1, 1);
$cell->writeText('This text will stay normal', $font, $paragraph);
$cell->writeText('', $font, $paragraph);
$cell->addList($enum);

![a](https://f.cloud.github.com/assets/4965915/961174/6398533c-04cc-11e3-8e47-4c520f631aac.JPG)

**Comment by sigma-z** [comment]
f0314bcb2291d7211ea278ba09135e6b5af82b70 should fix your problem. If not, plz let me know
