### ISSUE TITLE
Save converted rtf file to database

### ISSUE THREAD

**Issue by victorkurauchi** [phprtflite/PHPRtfLite#8]
Is it possible to save the converted rtf content to database instead saving to a file ?
I mean, i would like to get the stream content to handle it and save to database.

```
$rtf = new PHPRtfLite();

 //Font
 $times12 = new PHPRtfLite_Font(12, 'Times new Roman');

 //Section
 $sect = $rtf->addSection();

 //Write utf-8 encoded text.
 //Text is from file. But you can use another resouce: db, sockets and other
 $content = $sect->writeText('<p>lorem ipsum</p>', $times12, null);

 // How can i save to database instead save to a file here ?
 // save rft document
 // $rtf->save($dir . '/generated/' . basename(__FILE__, '.php') . '.rtf');
```

**Comment by sigma-z** [comment]
Hello

With $rtf->getContent() you can get the content of the rtf file. Then the string can be saved in your database.

**Comment by victorkurauchi** [comment]
Thanks for the response @sigma-z, i tried this way but didn't work ( Did i miss something ? )

```
$rtf = new PHPRtfLite();

//Font
$times12 = new PHPRtfLite_Font(12, 'Verdana');

 //Section
 $sect = $rtf->addSection();

 //Write utf-8 encoded text.
 //Text is from file. But you can use another resouce: db, sockets and other
 $content = $sect->writeText($row['laudo'], $times12, null);

 $result = $rtf->getContent();
```

When i persist $result to the database, the saved result comes with RTF format but with HTML tags inside the content... 

Something like that...
{rtf:\contentcontent<p>content<p><h1>morehtmltags</h1>}} 

Got a clue about that ? Thanks!

**Comment by victorkurauchi** [comment]
the original html has inline-style, is that a problem ? thanks

**Comment by sigma-z** [comment]
I tested your code with html tags:

$content = $sect->writeText('&lt;p&gt;lorem ipsum&lt;/p&gt;', $times12, null);
$result = $rtf->getContent();
var_dump($result);

And it worked for me... If the file content contains html tags you should provide the forth argument as FALSE of $sect->writeText() to disable the converting of html tags to rtf code. If this will work, there should be a problem with the converting, I guess. If so, you may provide me an example html file that produces the problem.

**Comment by victorkurauchi** [comment]
I tried the way you post, but no success yet... Did you try to persist to database ?
Reading the function writeText() comments, i saw that possible tags don't include < div >, < p >, and another tags. Is that right or is outdated ?

```
{\rtf\ansi\deff0
{\fonttbl{\f0 Times New Roman;}{\f1 Verdana;}}
{\colortbl;\red0\green0\blue0;}
{\info
}
\paperw11907 \paperh16443 \deftab1298 \margl1701 \margr1701 \margt567 \margb1134 \pgnstart1\ftnnar \aftnnrlc          \   ftnstart1 \aftnstart1 
{\fs24 \f1 < p>lorem ipsum</p>}

}
```

This is the result on mysql. Paragraph tag still there ... that's my main problem... When i save to database, the format RTF has the html tags mentioned above inside it.

Thanks man, hope we can solve this.

**Comment by victorkurauchi** [comment]
Note: using var_dump($result) i see the rtf content correctly. My problem is persisting to datatbase, it breaks some div tags etc... But now i need to handle my input content. Thanks!

**Comment by victorkurauchi** [comment]
var_dump result:

```
{\colortbl;\red0\green0\blue0;}
{\info
}
\paperw11907 \paperh16443 \deftab1298 \margl1701 \margr1701 \margt567 \margb1134 \pgnstart1\ftnnar \aftnnrlc      \ftnstart1 \aftnstart1 
\pard \ql {\fs24 \f1 <div align='center'><span style='color: #000000; font-family: Arial; font-size: medium;'>\b     TOMOGRAFIA COMPUTADORIZADA DO ABDOME SUPERIOR\b0 </span></div><div align='justify'><span     style='color: #000000; font-family: Arial; font-size: medium;'>\b '... (length=4796)
```

The syntax has html tags inside RTF content. Is it correct ? That was my last code review position trying to solve my issue.

Best regards.

**Comment by victorkurauchi** [comment]
I saved the generated RTF content to a .log file.
Result:

```
//Rtf document
$rtf = new PHPRtfLite();

//Font
$times12 = new PHPRtfLite_Font(12, 'Verdana');

//Section
$sect = $rtf->addSection();

$text = "<p>HAHAHAHHA</p><h2>Test</h2>";

//Text is from file. But you can use another resouce: db, sockets and other
$content = $sect->writeText($text, $times12, new PHPRtfLite_ParFormat());

$result = $rtf->getContent();

$year  = date('Y');
$month = date('m');
$day   = date('d');
$path  = "log/{$year}/{$month}/{$day}";

if (!is_dir($path)) mkdir($path, 0777, true);

$filename = $path . '/teste.log';
$str      = '//'. "\r\n";
$str     .= "Log registrado em: " . date("d/m/Y H:i:s") . "\r\n";

if(file_exists($filename))  $fp = @fopen($filename,"a");                                                            #Append
else                        $fp = @fopen($filename,"w");                                                            #Write

@fputs($fp, "\r\n" . $str . "\r\n" . 'Registro: ' . $result .  "\r\n". "//" .  "\r\n");                             #Put content.

fclose($fp);
```

The .log result was: 

```
 {\rtf\ansi\deff0
 {\fonttbl{\f0 Times New Roman;}{\f1 Verdana;}}
 {\colortbl;\red0\green0\blue0;}
 {\info
 }
 \paperw11907 \paperh16443 \deftab1298 \margl1701 \margr1701 \margt567 \margb1134 \pgnstart1\ftnnar    \aftnnrlc \ftnstart1 \aftnstart1 
 \pard \ql {\fs24 \f1 <p>HAHAHAHHA</p><h2>Testando</h2>}}
```

## 

With var_dump:

```
string '{\rtf\ansi\deff0
{\fonttbl{\f0 Times New Roman;}{\f1 Verdana;}}
{\colortbl;\red0\green0\blue0;}
{\info
}
\paperw11907 \paperh16443 \deftab1298 \margl1701 \margr1701 \margt567 \margb1134 \pgnstart1\ftnnar  \aftnnrlc \ftnstart1 \aftnstart1 
\pard \ql {\fs24 \f1 <p>HAHAHAHHA</p><h2>Test</h2>}

}' (length=300)
```

Man, sorry about pissing you off. It's just really important to me . I appreciate any help.

**Comment by ctrlaltca** [comment]
As soon as you are able to code and understand php code, just digging in PHPRtfLite_Container_Base::writeText() you'll see the following comment:

``` php
    /**
     * writes text to container.
     *
     * @param string $text Text. Also you can use html style tags. Possible tags:<br>
     *   strong, b- bold; <br>
     *   em - ; <br>
     *   i - italic; <br>
     *   u - underline; <br>
     *   br - line break; <br>
     *   chdate - current date; <br>
     *   chdpl - current date in long format; <br>
     *   chdpa - current date in abbreviated format; <br>
     *   chtime - current time; <br>
     *   chpgn, pagenum - page number ; <br>
     *   tab - tab
     *   sectnum - section number; <br>
     *   line - line break; <br>
     *   page - page break; <br>
     *   sect - section break; <br>
     * @param   PHPRtfLite_Font         $font               font of text
     * @param   PHPRtfLite_ParFormat    $parFormat          paragraph format, if null, text is written in the same paragraph.
     * @param   boolean                 $convertTagsToRtf   if false, then html style tags are not replaced with rtf code
     * @return  PHPRtfLite_Element
     */
```

So currently both the "p" and the "h2" tags are not supported.
I think it won't be hard to implement "p" since it has a direct counterpart in rtf (\par); about "h2", as far as i know there are not predetermined paragraph formats like "heading2" so it won't be easy to convert it.
My advice can only be to avoid the html tags and directly use the rtf methods.

**Comment by victorkurauchi** [comment]
Thanks for the response @ctrlaltca !!! I'll give a try. 
Thanks for all. Best regards
